name: DockerWebSite
summary: Private app service running a docker container
description: ...
templatePath: main.bicep
parameters: 
- id: "image"
  name: "Docker Image"
  type: "string"
  required: true
  default: "mcr.microsoft.com/appsvc/staticsite:latest"
